sonar.projectKey=WorkNest_Mobile
sonar.projectName=WorkNest Mobile
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gen.dart,**/generated/**
