-- Malaysian public holidays
--
-- Used by the mobile app so public holidays are not counted as "Absent" on the
-- attendance screen. Seeded from Google's public Malaysia holiday calendar
-- (observances such as Valentine's Day are excluded).
--   regions = null  -> nationwide holiday
--   regions = text  -> only in the listed states (e.g. 'Sabah, Labuan')

begin;

create table if not exists public.public_holidays (
  date    date not null,
  name    text not null,
  regions text,
  primary key (date, name)
);

alter table public.public_holidays enable row level security;

drop policy if exists emp_select_public_holidays on public.public_holidays;
create policy emp_select_public_holidays on public.public_holidays
  for select to authenticated using (true);

insert into public.public_holidays (date, name, regions) values
  ('2021-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2021-01-28', 'Thaipusam (regional holiday)', 'Johor, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2021-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2021-02-12', 'Chinese New Year''s Day', null),
  ('2021-02-13', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2021-02-13', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2021-03-11', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2021-04-02', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2021-04-29', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2021-05-01', 'Labour Day', null),
  ('2021-05-13', 'Hari Raya Puasa', null),
  ('2021-05-14', 'Hari Raya Puasa Holiday Day 2', null),
  ('2021-05-26', 'Wesak Day', null),
  ('2021-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2021-05-31', 'Harvest Festival observed (regional holiday)', 'Sabah, Labuan'),
  ('2021-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2021-06-07', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2021-07-20', 'Hari Raya Haji', null),
  ('2021-07-20', 'Hari Raya Haji holiday', null),
  ('2021-07-21', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kedah, Kelantan, Perlis, Terengganu'),
  ('2021-08-10', 'Muharram', null),
  ('2021-08-31', 'Malaysia''s National Day', null),
  ('2021-09-16', 'Malaysia Day', null),
  ('2021-10-19', 'The Prophet Muhammad''s Birthday', null),
  ('2021-11-04', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2021-12-25', 'Christmas Day', null),
  ('2022-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-01-18', 'Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2022-02-01', 'Chinese New Year''s Day', null),
  ('2022-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-02-02', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2022-02-02', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-03-01', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2022-04-15', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2022-04-19', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-05-01', 'Labour Day', null),
  ('2022-05-02', 'Hari Raya Puasa', null),
  ('2022-05-03', 'Hari Raya Puasa Holiday Day 2', null),
  ('2022-05-04', 'Labour Day observed', null),
  ('2022-05-15', 'Wesak Day', null),
  ('2022-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2022-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2022-06-06', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2022-07-10', 'Hari Raya Haji', null),
  ('2022-07-10', 'Hari Raya Haji holiday', null),
  ('2022-07-11', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kelantan, Terengganu'),
  ('2022-07-30', 'Muharram', null),
  ('2022-08-31', 'Malaysia''s National Day', null),
  ('2022-09-16', 'Malaysia Day', null),
  ('2022-10-09', 'The Prophet Muhammad''s Birthday', null),
  ('2022-10-10', 'The Prophet Muhammad''s Birthday Holiday (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-10-24', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2022-11-18', 'Election Eve Holiday (regional holiday)', 'Johor, Kedah, Kelantan, Negeri Sembilan, Penang, Sabah, Sarawak, Selangor, Terengganu'),
  ('2022-11-19', 'General Elections (regional holiday)', 'Johor, Kedah, Kelantan, Sabah, Sarawak'),
  ('2022-11-20', 'Day off for Election Eve Holiday (regional holiday)', 'Johor, Kedah, Kelantan'),
  ('2022-11-28', 'Elections Victory Public Holiday', null),
  ('2022-12-25', 'Christmas Day', null),
  ('2022-12-26', 'Christmas Day observed', null),
  ('2023-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-01-02', 'New Year''s Day observed (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-01-22', 'Chinese New Year''s Day', null),
  ('2023-01-23', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2023-01-23', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-02-05', 'Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2023-02-18', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2023-04-07', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2023-04-08', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-04-21', 'Hari Raya Puasa Holiday', null),
  ('2023-04-22', 'Hari Raya Puasa', null),
  ('2023-04-23', 'Hari Raya Puasa Holiday Day 2', null),
  ('2023-05-01', 'Labour Day', null),
  ('2023-05-04', 'Wesak Day', null),
  ('2023-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2023-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2023-06-05', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2023-06-28', 'Day of Arafat (regional holiday)', 'Kelantan, Terengganu'),
  ('2023-06-29', 'Hari Raya Haji', null),
  ('2023-06-30', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kelantan, Terengganu'),
  ('2023-07-19', 'Muharram', null),
  ('2023-08-31', 'Malaysia''s National Day', null),
  ('2023-09-16', 'Malaysia Day', null),
  ('2023-09-28', 'The Prophet Muhammad''s Birthday', null),
  ('2023-11-12', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2023-12-25', 'Christmas Day', null),
  ('2024-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-01-25', 'Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2024-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-02-08', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2024-02-10', 'Chinese New Year''s Day', null),
  ('2024-02-11', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu, Terengganu'),
  ('2024-02-11', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-02-12', 'Chinese New Year Holiday (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-03-28', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-03-29', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2024-04-10', 'Hari Raya Puasa', null),
  ('2024-04-11', 'Hari Raya Puasa Holiday Day 2', null),
  ('2024-05-01', 'Labour Day', null),
  ('2024-05-22', 'Wesak Day', null),
  ('2024-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2024-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2024-06-03', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2024-06-16', 'Day of Arafat (regional holiday)', 'Kelantan, Terengganu'),
  ('2024-06-17', 'Hari Raya Haji', null),
  ('2024-06-18', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kelantan, Terengganu'),
  ('2024-07-07', 'Muharram', null),
  ('2024-07-08', 'Muharram Holiday (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-08-31', 'Malaysia''s National Day', null),
  ('2024-09-16', 'Malaysia Day', null),
  ('2024-09-16', 'The Prophet Muhammad''s Birthday', null),
  ('2024-10-31', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2024-12-25', 'Christmas Day', null),
  ('2025-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2025-01-27', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2025-01-29', 'Chinese New Year''s Day', null),
  ('2025-01-30', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2025-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2025-02-11', 'Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2025-03-18', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2025-03-31', 'Hari Raya Puasa', null),
  ('2025-04-01', 'Hari Raya Puasa Holiday Day 2', null),
  ('2025-04-18', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2025-05-01', 'Labour Day', null),
  ('2025-05-12', 'Wesak Day', null),
  ('2025-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2025-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2025-06-02', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2025-06-06', 'Day of Arafat (regional holiday)', 'Kelantan, Terengganu'),
  ('2025-06-07', 'Hari Raya Haji', null),
  ('2025-06-08', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kelantan, Terengganu'),
  ('2025-08-31', 'Malaysia''s National Day', null),
  ('2025-09-05', 'The Prophet Muhammad''s Birthday', null),
  ('2025-09-15', 'Malaysia Day Holiday', null),
  ('2025-09-16', 'Malaysia Day', null),
  ('2025-10-20', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2025-12-25', 'Christmas Day', null),
  ('2026-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-01-17', 'Isra and Mi''raj (regional holiday)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2026-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-02-01', 'Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2026-02-02', 'Day off for Thaipusam (regional holiday)', 'Johor, Kedah, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2026-02-02', 'Federal Territory Day observed (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-02-17', 'Chinese New Year''s Day', null),
  ('2026-02-18', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2026-02-18', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-03-07', 'Nuzul Al-Quran (regional holiday)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-03-20', 'Hari Raya Puasa Holiday', null),
  ('2026-03-21', 'Hari Raya Puasa', null),
  ('2026-04-03', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2026-05-01', 'Labour Day', null),
  ('2026-05-26', 'Day of Arafat (regional holiday)', 'Kelantan, Terengganu'),
  ('2026-05-27', 'Hari Raya Haji', null),
  ('2026-05-28', 'Hari Raya Haji (Day 2) (regional holiday)', 'Kelantan, Terengganu'),
  ('2026-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2026-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2026-05-31', 'Wesak Day', null),
  ('2026-06-01', 'Second Day of Harvest Festival observed (regional holiday)', 'Sabah, Labuan'),
  ('2026-06-01', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2026-06-17', 'Muharram', null),
  ('2026-08-25', 'The Prophet Muhammad''s Birthday', null),
  ('2026-08-31', 'Malaysia''s National Day', null),
  ('2026-09-16', 'Malaysia Day', null),
  ('2026-11-08', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2026-12-25', 'Christmas Day', null),
  ('2027-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2027-01-06', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2027-01-22', 'Thaipusam (regional holiday)', 'Johor, Negeri Sembilan, Penang, Perak, Selangor, Kuala Lumpur, Putrajaya'),
  ('2027-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2027-02-06', 'Chinese New Year''s Day', null),
  ('2027-02-07', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2027-02-07', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2027-02-24', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2027-03-10', 'Hari Raya Puasa (tentative)', null),
  ('2027-03-11', 'Hari Raya Puasa Holiday Day 2 (tentative)', null),
  ('2027-03-26', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2027-05-01', 'Labour Day', null),
  ('2027-05-16', 'Day of Arafat (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2027-05-17', 'Hari Raya Haji (tentative)', null),
  ('2027-05-18', 'Hari Raya Haji (Day 2) (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2027-05-20', 'Wesak Day', null),
  ('2027-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2027-05-31', 'Harvest Festival observed (regional holiday)', 'Sabah, Labuan'),
  ('2027-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2027-06-06', 'Muharram (tentative)', null),
  ('2027-06-07', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2027-08-15', 'The Prophet Muhammad''s Birthday (tentative)', null),
  ('2027-08-31', 'Malaysia''s National Day', null),
  ('2027-09-16', 'Malaysia Day', null),
  ('2027-10-28', 'Diwali (regional holiday)', 'Johor, Kedah, Kelantan, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2027-12-25', 'Christmas Day', null),
  ('2027-12-26', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2028-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2028-01-26', 'Chinese New Year''s Day', null),
  ('2028-01-27', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2028-01-27', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2028-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2028-02-13', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2028-02-27', 'Hari Raya Puasa (tentative)', null),
  ('2028-02-28', 'Hari Raya Puasa Holiday Day 2 (tentative)', null),
  ('2028-04-14', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2028-05-01', 'Labour Day', null),
  ('2028-05-04', 'Day of Arafat (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2028-05-05', 'Hari Raya Haji (tentative)', null),
  ('2028-05-06', 'Hari Raya Haji (Day 2) (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2028-05-25', 'Muharram (tentative)', null),
  ('2028-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2028-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2028-06-05', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2028-08-03', 'The Prophet Muhammad''s Birthday (tentative)', null),
  ('2028-08-31', 'Malaysia''s National Day', null),
  ('2028-09-16', 'Malaysia Day', null),
  ('2028-12-14', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2028-12-25', 'Christmas Day', null),
  ('2029-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2029-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2029-02-01', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2029-02-13', 'Chinese New Year''s Day', null),
  ('2029-02-14', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2029-02-14', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2029-02-15', 'Hari Raya Puasa (tentative)', null),
  ('2029-02-16', 'Hari Raya Puasa Holiday Day 2 (tentative)', null),
  ('2029-03-30', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2029-04-23', 'Day of Arafat (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2029-04-24', 'Hari Raya Haji (tentative)', null),
  ('2029-04-25', 'Hari Raya Haji (Day 2) (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2029-05-01', 'Labour Day', null),
  ('2029-05-15', 'Muharram (tentative)', null),
  ('2029-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2029-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2029-06-04', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2029-07-24', 'The Prophet Muhammad''s Birthday (tentative)', null),
  ('2029-08-31', 'Malaysia''s National Day', null),
  ('2029-09-16', 'Malaysia Day', null),
  ('2029-12-04', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2029-12-25', 'Christmas Day', null),
  ('2030-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2030-01-22', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2030-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2030-02-03', 'Chinese New Year''s Day', null),
  ('2030-02-04', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2030-02-04', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2030-02-05', 'Hari Raya Puasa (tentative)', null),
  ('2030-02-06', 'Hari Raya Puasa Holiday Day 2 (tentative)', null),
  ('2030-04-13', 'Day of Arafat (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2030-04-14', 'Hari Raya Haji (tentative)', null),
  ('2030-04-15', 'Hari Raya Haji (Day 2) (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2030-04-19', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2030-05-01', 'Labour Day', null),
  ('2030-05-04', 'Muharram (tentative)', null),
  ('2030-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2030-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2030-06-03', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2030-07-13', 'The Prophet Muhammad''s Birthday (tentative)', null),
  ('2030-08-31', 'Malaysia''s National Day', null),
  ('2030-09-16', 'Malaysia Day', null),
  ('2030-11-23', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2030-12-25', 'Christmas Day', null),
  ('2031-01-01', 'New Year''s Day (regional holiday)', 'Malacca, Negeri Sembilan, Pahang, Penang, Perak, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2031-01-11', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya'),
  ('2031-01-23', 'Chinese New Year''s Day', null),
  ('2031-01-24', 'Chinese New Year Holiday (regional holiday)', 'Kelantan, Terengganu'),
  ('2031-01-24', 'Second Day of Chinese New Year (regional holiday)', 'Johor, Kedah, Malacca, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Selangor, Sabah, Sarawak, Kuala Lumpur, Labuan, Putrajaya'),
  ('2031-01-25', 'Hari Raya Puasa (tentative)', null),
  ('2031-01-26', 'Hari Raya Puasa Holiday Day 2 (tentative)', null),
  ('2031-02-01', 'Federal Territory Day (regional holiday)', 'Kuala Lumpur, Labuan, Putrajaya'),
  ('2031-04-02', 'Day of Arafat (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2031-04-03', 'Hari Raya Haji (tentative)', null),
  ('2031-04-04', 'Hari Raya Haji (Day 2) (regional holiday) (tentative)', 'Kelantan, Terengganu'),
  ('2031-04-11', 'Good Friday (regional holiday)', 'Sabah, Sarawak'),
  ('2031-04-23', 'Muharram (tentative)', null),
  ('2031-05-01', 'Labour Day', null),
  ('2031-05-30', 'Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2031-05-31', 'Second Day of Harvest Festival (regional holiday)', 'Sabah, Labuan'),
  ('2031-06-02', 'The Yang di-Pertuan Agong''s Birthday', null),
  ('2031-07-02', 'The Prophet Muhammad''s Birthday (tentative)', null),
  ('2031-08-31', 'Malaysia''s National Day', null),
  ('2031-09-01', 'Day off for Malaysia''s National Day', null),
  ('2031-09-16', 'Malaysia Day', null),
  ('2031-11-12', 'Isra and Mi''raj (regional holiday) (tentative)', 'Kedah, Negeri Sembilan, Perlis, Terengganu'),
  ('2031-12-25', 'Christmas Day', null),
  ('2031-12-31', 'Nuzul Al-Quran (regional holiday) (tentative)', 'Kelantan, Pahang, Penang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya')
on conflict (date, name) do update set regions = excluded.regions;

commit;
